@host = http://localhost:3000/api/auth
@contentType = application/x-www-form-urlencoded
# @contentType = application/json


### login
POST {{host}}/login
content-type: {{contentType}}

&email=example@gmail.com
&password=example231

### register
POST {{host}}/register
content-type: {{contentType}}

&name=Kylie
&email=kylie@gmail.com
&password=kylie231

### Validate Email
GET {{host}}/validate-email/ABC

### validate Email
GET http://localhost:3000/api/auth/validate-email/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1aXNpbmhvdGZAZ21haWwuY29tIiwiaWF0IjoxNzExOTM5ODQwLCJleHAiOjE3MTE5NDcwNDB9.SfSPyjJMdbSlG9UUBFECXiX-Gd2QM8tI11QWIVb89Mg
